[2024-08-27T06:01:41.663+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-27T06:01:41.742+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Spark.get_seoul_api manual__2024-08-27T06:01:39.299233+00:00 [queued]>
[2024-08-27T06:01:41.781+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Spark.get_seoul_api manual__2024-08-27T06:01:39.299233+00:00 [queued]>
[2024-08-27T06:01:41.783+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2024-08-27T06:01:41.827+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): get_seoul_api> on 2024-08-27 06:01:39.299233+00:00
[2024-08-27T06:01:41.839+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1504) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-27T06:01:41.841+0000] {standard_task_runner.py:72} INFO - Started process 1507 to run task
[2024-08-27T06:01:41.838+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Spark', 'get_seoul_api', 'manual__2024-08-27T06:01:39.299233+00:00', '--job-id', '252', '--raw', '--subdir', 'DAGS_FOLDER/Seoul_spark.py', '--cfg-path', '/tmp/tmpur48tjm4']
[2024-08-27T06:01:41.842+0000] {standard_task_runner.py:105} INFO - Job 252: Subtask get_seoul_api
[2024-08-27T06:01:41.930+0000] {task_command.py:467} INFO - Running <TaskInstance: Spark.get_seoul_api manual__2024-08-27T06:01:39.299233+00:00 [running]> on host 1c1d52fdfc5f
[2024-08-27T06:01:42.095+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Spark' AIRFLOW_CTX_TASK_ID='get_seoul_api' AIRFLOW_CTX_EXECUTION_DATE='2024-08-27T06:01:39.299233+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-27T06:01:39.299233+00:00'
[2024-08-27T06:01:42.097+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-27T06:01:42.353+0000] {Seoul_spark.py:16} INFO - {'status': 'ok', 'data': {'aqi': 42, 'idx': 5508, 'attributions': [{'url': 'https://www.airkorea.or.kr/', 'name': 'South Air Korea Environment Corporation (대기오염실시간공개시스템)', 'logo': 'SouthKorea-AirKorea.png'}, {'url': 'http://cleanair.seoul.go.kr/', 'name': 'Seoul Clean Air Pollution Information (서울특별시 기후대기환경정보)', 'logo': 'SouthKorea-Seoul.png'}, {'url': 'https://waqi.info/', 'name': 'World Air Quality Index Project'}], 'city': {'geo': [37.566535, 126.9779692], 'name': 'Seoul (서울)', 'url': 'https://aqicn.org/city/seoul', 'location': ''}, 'dominentpol': 'pm25', 'iaqi': {'co': {'v': 5.7}, 'h': {'v': 63.6}, 'no2': {'v': 22.2}, 'o3': {'v': 24.8}, 'p': {'v': 996}, 'pm10': {'v': 22}, 'pm25': {'v': 42}, 'r': {'v': 99}, 'so2': {'v': 5}, 't': {'v': 27.4}, 'w': {'v': 2}}, 'time': {'s': '2024-08-27 14:00:00', 'tz': '+09:00', 'v': 1724767200, 'iso': '2024-08-27T14:00:00+09:00'}, 'forecast': {'daily': {'o3': [{'avg': 17, 'day': '2024-08-25', 'max': 55, 'min': 1}, {'avg': 2, 'day': '2024-08-26', 'max': 18, 'min': 1}, {'avg': 7, 'day': '2024-08-27', 'max': 61, 'min': 1}, {'avg': 10, 'day': '2024-08-28', 'max': 33, 'min': 1}, {'avg': 9, 'day': '2024-08-29', 'max': 30, 'min': 1}, {'avg': 6, 'day': '2024-08-30', 'max': 29, 'min': 1}, {'avg': 6, 'day': '2024-08-31', 'max': 41, 'min': 1}, {'avg': 1, 'day': '2024-09-01', 'max': 1, 'min': 1}], 'pm10': [{'avg': 47, 'day': '2024-08-26', 'max': 49, 'min': 46}, {'avg': 46, 'day': '2024-08-27', 'max': 46, 'min': 40}, {'avg': 31, 'day': '2024-08-28', 'max': 46, 'min': 19}, {'avg': 18, 'day': '2024-08-29', 'max': 27, 'min': 10}, {'avg': 13, 'day': '2024-08-30', 'max': 16, 'min': 7}, {'avg': 32, 'day': '2024-08-31', 'max': 44, 'min': 17}, {'avg': 38, 'day': '2024-09-01', 'max': 46, 'min': 28}, {'avg': 44, 'day': '2024-09-02', 'max': 46, 'min': 28}], 'pm25': [{'avg': 137, 'day': '2024-08-26', 'max': 138, 'min': 129}, {'avg': 106, 'day': '2024-08-27', 'max': 120, 'min': 86}, {'avg': 90, 'day': '2024-08-28', 'max': 119, 'min': 68}, {'avg': 54, 'day': '2024-08-29', 'max': 78, 'min': 30}, {'avg': 45, 'day': '2024-08-30', 'max': 56, 'min': 30}, {'avg': 83, 'day': '2024-08-31', 'max': 102, 'min': 55}, {'avg': 116, 'day': '2024-09-01', 'max': 138, 'min': 89}, {'avg': 124, 'day': '2024-09-02', 'max': 138, 'min': 89}], 'uvi': [{'avg': 0, 'day': '2024-08-26', 'max': 0, 'min': 0}, {'avg': 1, 'day': '2024-08-27', 'max': 5, 'min': 0}, {'avg': 1, 'day': '2024-08-28', 'max': 7, 'min': 0}, {'avg': 1, 'day': '2024-08-29', 'max': 7, 'min': 0}, {'avg': 1, 'day': '2024-08-30', 'max': 7, 'min': 0}, {'avg': 2, 'day': '2024-08-31', 'max': 8, 'min': 0}]}}, 'debug': {'sync': '2024-08-27T15:01:08+09:00'}}}
[2024-08-27T06:01:42.358+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Seoul_spark.py", line 17, in _get_seoul_api
    with open(str("/opt/airflow/dags/AirPollutionSeoul/realtime"+str(datetime.datetime.now().date())+".json"),"w") as f :
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/AirPollutionSeoul/realtime2024-08-27.json'
[2024-08-27T06:01:42.396+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=Spark, task_id=get_seoul_api, run_id=manual__2024-08-27T06:01:39.299233+00:00, execution_date=20240827T060139, start_date=20240827T060141, end_date=20240827T060142
[2024-08-27T06:01:42.437+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-27T06:01:42.438+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 252 for task get_seoul_api ([Errno 2] No such file or directory: '/opt/airflow/dags/AirPollutionSeoul/realtime2024-08-27.json'; 1507)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Seoul_spark.py", line 17, in _get_seoul_api
    with open(str("/opt/airflow/dags/AirPollutionSeoul/realtime"+str(datetime.datetime.now().date())+".json"),"w") as f :
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/AirPollutionSeoul/realtime2024-08-27.json'
[2024-08-27T06:01:42.479+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-08-27T06:01:42.525+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-27T06:01:42.528+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
